### ISSUE TITLE
Unable to build docker file

### ISSUE THREAD

**Issue by paulywill** [matthieucan/quebec-monitoring#6]
Is this project still maintained or work?

I'm getting the following error  `E: Unable to locate package kaji`

The http://kaji-project.github.io/ is showing a 404.

Is there a substitute for kaji?
Is there at least a screenshot of this project working?

**Comment by matthieucan** [comment]
This project was last maintained at https://github.com/savoirfairelinux/quebec-monitoring but AFAICT it is not maintained anymore.
Kaji was a set of packages built on openbuildservice, their sources are still there: https://github.com/kaji-project.
I sadly don't have a screenshot, and archive.org doesn't show anything useful either. But if I can be of any help, let me know.
